### ISSUE TITLE
[feature] move from oclif to clipanion

### ISSUE THREAD

**Issue by TFK70** [Atlantis-Lab/actl#122]
### С чем связан запрос на фичу?

Oclif блокирует переход на yarn2

### Расскажите как вы это себе видите

```javascript
class YarnInstall extends Command {
  frozenLockfile = Option.Boolean(`--frozen-lockfile`, false);
  maxRetries = Option.String(`--max-retries`, `0`, {validator: isPositiveInteger});

  static paths = [Command.Default, [`install`]];
  async execute() {
    this.context.stdout.write(`Running an install: ${this.context.cwd}, with ${this.maxRetries} max retries\n`);
  }
}

cli.register(YarnInstall);
cli.runExit(args, Cli.defaultContext);
```

### Приложите примеры реализаций

https://github.com/arcanis/clipanion/blob/master/sources/demos/advanced.ts

**Comment by TFK70** [comment]
@TorinAsakura если скрипт установлен локально в проекте - его можно заекзекутить через `yarn <command>` (в нашем случае `yarn actl lint` или `yarn run actl commit` и т.д.), но мы так не делаем. Наш случай - это сделать следующее в корневом package.json:
```javascript
"scripts": {
   "commit": "actl commit"
}|
```
И запускать через `yarn commit`. Так тоже все работает, протестил на втором ярне - аналогично. Это все достигается секцией bin в package.json

Единственный вопрос - как это работает глобально. Я так и не нашел что происходит с yarn global в v2, а если точнее то глобала там вообще пока нет, но на первом ярне команда при таком подходе должна отрабатывать как нативная (просто через actl)

Да, и на данный момент для воспроизведения функционала необходимо установить все  пакеты использующие clipanion как зависимости, только тогда скрипт появится в bin

**Comment by TorinAsakura** [comment]
@TFK70 от меня что-то требуется?
по ярну второму можете в коопе поработать с @aenoralanar

**Comment by TFK70** [comment]
> @TFK70 от меня что-то требуется?
> по ярну второму можете в коопе поработать с @aenoralanar

Пока нет, продолжу другие пакеты переводить
Полноценно протестировать получится только после паблиша
